const ROUTINI = [
  [
    "<Router> + a routes array",
    "All routing is configured in one place (App.tsx): a typed array mapping each path to a component or a lazy import. The home feed is eager; everything else is code-split.",
  ],
  [
    "Lazy routes (code-splitting)",
    "Each page is a dynamic import(), so it ships as its own chunk. The Leaflet-powered Explore map — the heaviest screen — only downloads when you open it, keeping the initial bundle small.",
  ],
  [
    "<Link> + preload=\"hover\"",
    "Every navigation is a <Link>. With preload=\"hover\" the target route's chunk is fetched on pointer-enter, so by the time you click it's already cached — lazy navigation feels instant.",
  ],
  [
    "<Link> + View Transitions",
    "Tapping a feed row morphs its artwork, name and date straight into the artist hero (and back). It's a shared-element transition: the same view-transition-name is set on both pages and the browser animates between them — no animation library.",
  ],
  [
    "<Outlet>",
    "AppLayout renders the matched page inside a single <Outlet>. Crucially, the audio player and navigation live OUTSIDE that Outlet, so the <audio> element is never unmounted on navigation — that's how playback keeps going as you move between pages.",
  ],
  [
    "useParams",
    "The artist (/artist/:id), event (/event/:id), and notifications (/notifications/:id) pages read the route param. The open notification being a real URL means it's deep-linkable and back/forward works — /notifications and /notifications/:id share one lazy import so the page never remounts between them.",
  ],
  [
    "useLocation",
    "This very page is full-width with no events sidebar: AppLayout reads useLocation().path and drops the sidebar when you're on /about, handing the screen to the section nav on the left.",
  ],
  [
    "Catch-all \"*\"",
    "Any unmatched URL renders the 404 page.",
  ],
];

const SECTIONS = [
  ["overview", "Overview"],
  ["app", "What the app does"],
  ["architecture", "How it's built"],
  ["routini", "How routini is used"],
  ["stack", "Stack"],
  ["status", "Status"],
];

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-6 pt-12 first:pt-0">
      <h2 className="text-2xl font-bold tracking-tight">{title}</h2>
      <div className="mt-4 space-y-3 leading-relaxed text-text-dim">{children}</div>
    </section>
  );
}

export default function About() {
  return (
    <div className="mx-auto max-w-6xl px-8 pb-20 pt-16 sm:px-12 lg:pb-28 lg:pt-24">
      <div className="lg:grid lg:grid-cols-[12rem_minmax(0,1fr)] lg:gap-16">
        {/* Section nav — sticky in-page anchors, like a docs sidebar */}
        <aside className="hidden lg:block">
          <nav className="sticky top-0 flex flex-col gap-1 py-1 text-sm">
            <p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-text-faint">
              On this page
            </p>
            {SECTIONS.map(([id, label]) => (
              <a
                key={id}
                href={`#${id}`}
                className="rounded-md py-1 text-text-dim transition hover:text-text"
              >
                {label}
              </a>
            ))}
          </nav>
        </aside>

        {/* Content */}
        <div className="max-w-3xl">
          <header>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-text-faint">
              About this project
            </p>
            <h1 className="mt-3 text-6xl font-black tracking-tight sm:text-7xl lg:text-8xl">
              Sona
            </h1>
            <p className="mt-6 text-lg leading-relaxed text-text-dim">
              A music &amp; event-discovery app — find artists and shows
              happening near you, hear their music, and explore the local scene
              on a map. It's a{" "}
              <strong className="text-text">work-in-progress prototype</strong>,
              built to put <strong className="text-text">routini</strong> — a
              tiny, ~3&nbsp;KB TypeScript-first React router — through its paces
              in a realistic product rather than a toy example.
            </p>
          </header>

          <Section id="overview" title="Overview">
            <p>
              Sona is a single-page app with no backend. The dataset (artists,
              events, a shared 15-track song pool across six Creative Commons
              albums) is generated by a script and imported statically, so the
              whole thing is self-contained and deployable anywhere. The goal
              isn't to ship a music service — it's to exercise every routini
              feature inside a product that actually feels like one.
            </p>
          </Section>

          <Section id="app" title="What the app does">
            <p>
              The home feed ranks artists by distance from you ("1.7 km from
              you"), nearest first. Each artist has a page with their tracks, the
              events they'll play, and the other acts they're performing
              alongside. Events live both on an interactive map (Explore) and in
              a grid. A player docked at the bottom keeps playing while you
              browse, notifications are deep-linkable, and the whole app supports
              light and dark themes.
            </p>
          </Section>

          <Section id="architecture" title="How it's built">
            <p>
              A single layout component (<code className="text-text">AppLayout</code>)
              is the persistent shell: a top bar, an events sidebar (desktop) that
              becomes a bottom tab bar (mobile), one route{" "}
              <code className="text-text">&lt;Outlet&gt;</code>, and the player.
              Because the player sits outside the Outlet, audio survives
              navigation; its state (current track, queue, volume) lives in a
              small zustand store driving a single{" "}
              <code className="text-text">&lt;audio&gt;</code> element.
            </p>
            <p>
              Pages are self-contained — each reads what it needs from the URL
              (<code className="text-text">useParams</code>) and the static
              dataset, with no props drilled through the router. The Explore map
              is real (Leaflet + OpenStreetMap/CARTO tiles), themed to match
              light/dark, and only loads when you open it.
            </p>
          </Section>

          <Section id="routini" title="How routini is used">
            <p>
              routini ships eight exports and a handful of features; here's each
              one Sona exercises and how:
            </p>
            <ul className="mt-4 flex flex-col gap-4">
              {ROUTINI.map(([name, how]) => (
                <li key={name} className="border-l-2 border-border pl-4">
                  <code className="text-sm font-semibold text-text">{name}</code>
                  <p className="mt-1 text-sm leading-relaxed text-text-dim">
                    {how}
                  </p>
                </li>
              ))}
            </ul>
            <p className="mt-4 text-sm">
              Available but not yet wired in this prototype:{" "}
              <code className="text-text">&lt;Navigate&gt;</code>,{" "}
              <code className="text-text">useSearchParams</code>, and the
              imperative <code className="text-text">navigate()</code>.
            </p>
          </Section>

          <Section id="stack" title="Stack">
            <p>
              React 19 · TypeScript · Vite · Tailwind CSS v4 · routini · zustand
              (audio store) · Radix Slider · Leaflet / react-leaflet (Explore
              map).
            </p>
          </Section>

          <Section id="status" title="Status">
            <p>
              Prototype, actively in progress. Done so far: the feed, artist,
              event, explore map, events grid, notifications, this page,
              light/dark theming, and a responsive desktop↔mobile shell. Next up:
              an event-page pass, an in-app credits surface, a landing page, and
              a public deploy.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <a
                href="https://github.com/kebinbin/routini"
                target="_blank"
                rel="noreferrer"
                className="rounded-full bg-text px-4 py-2 text-sm font-medium text-bg transition hover:opacity-90"
              >
                routini on GitHub
              </a>
              <a
                href="https://github.com/kebinbin/routini/tree/main/examples/music-player"
                target="_blank"
                rel="noreferrer"
                className="rounded-full border border-border px-4 py-2 text-sm font-medium text-text-dim transition hover:text-text"
              >
                This demo's source
              </a>
            </div>
          </Section>
        </div>
      </div>
    </div>
  );
}
